apiVersion: v1
kind: Namespace
metadata:
  name: rbac-ex3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
  namespace: rbac-ex3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: rbac-ex3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: robot
      containers:
        - name: app
          image: busybox:1.36
          command:
            - sh
            - -c
            - sleep 3600
