apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: skillshop
  labels: { app: frontend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: skilleat/skillshop-frontend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_SVC_URL
              value: http://product-svc:8080
            - name: ORDER_SVC_URL
              value: http://order-svc:8080
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: skillshop
spec:
  selector: { app: frontend }
  ports:
    - port: 8080
      targetPort: 8080
