apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skillshop
  namespace: skillshop
spec:
  ingressClassName: nginx
  rules:
    - host: skillshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
